# Generated by Django 4.1.7 on 2023-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_uname", models.CharField(max_length=200)),
                ("cart_product_id", models.IntegerField()),
                ("cart_quantity", models.IntegerField()),
                ("cart_total", models.FloatField(default=0)),
                ("order_timeed", models.CharField(max_length=200)),
            ],
        ),
    ]
